/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.docs;

/**
 * Some Docs HEre
 */
public class App {

    /**
     * Yippe Skippe
     * @return Hello world as string
     */
    public String getGreeting() {
        return "Hello world.";
    }

    /**
     * Just the main method.
     * @param args arguments
     */
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
